plugins {
    id 'java'
    id 'org.springframework.boot' version '4.1.0'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'
description = 'Read'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    // 1. Spring Web
    implementation 'org.springframework.boot:spring-boot-starter-web'
    // 2. Spring Data JPA
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    // 3. Spring Data MongoDB
    implementation 'org.springframework.boot:spring-boot-starter-data-mongodb'
    // 4. Kafka
    implementation 'org.springframework.boot:spring-boot-starter-kafka'

    // 5. Lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    // 6. Spring Boot DevTools
    developmentOnly 'org.springframework.boot:spring-boot-devtools'

    // 7. MySQL Driver
    runtimeOnly 'com.mysql:mysql-connector-j'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}